tasks:
  - name: install-dependencies
    before: |
      printf 'export PATH="$HOME%s:$PATH"\n' "/apache-cassandra/bin" >> $HOME/.bashrc
      printf 'export PATH="$HOME%s:$PATH"\n' "/apache-cassandra/tools/bin" >> $HOME/.bashrc
      printf 'unset JAVA_TOOL_OPTIONS\n' >> $HOME/.bashrc
    init: ""
    command: ""
ports:
  - port: 9042
    onOpen: ignore
  - port: 7000
    onOpen: ignore
  - port: 7199
    onOpen: ignore 
github:
  prebuilds:
    main: true
vscode:
   extensions:
    - https://github.com/hemidactylus/katapod/releases/download/1.1.0-beta2/katapod-1.1.0-beta2.vsix

